name: "FAP: Build and lint"
on: [push, pull_request]
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: 'ufbt: Build for release branch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app
        with:
          sdk-channel: release
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
      # You can remove this step if you don't want to check source code formatting
      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        with:
          # skip SDK setup, we already did it in previous step
          skip-setup: true
          task: lint
