name: Build

on:
  push:
    branches:
      - main
      - develop

env:
  firmware_version: '0.101.2'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flipper Zero Firmware
        uses: actions/checkout@v3
        with:
          repository: 'flipperdevices/flipperzero-firmware'
          ref: ${{ env.firmware_version }}
          submodules: true
      - name: Checkout flipper-enigma
        uses: actions/checkout@v3
        with:
          path: 'applications_user/flipper-enigma'
      - name: Build FAPs
        run: ./fbt COMPACT=1 DEBUG=0 faps
      - name: Check flipper-enigma Built
        run: test -f build/f7-firmware-C/.extapps/enigma.fap
      - name: Check flipper-enigma Size
        run: ls -l --block-size=K build/f7-firmware-C/.extapps/enigma.fap
