name: "Dev - Build & Upload FAP"
on:
  push:
    branches:
      - dev
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: "Build: Dev"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Flipper Zero ufbt action
      # https://github.com/flipperdevices/flipperzero-ufbt-action
      - name: "Build"
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          app-dir: ./fap
          sdk-channel: dev

      - name: "Create Zip Archive (dev)"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-dev-${{ steps.build-app.outputs.suffix }}.zip
          path: ${{ steps.build-app.outputs.fap-artifacts }}
