name: Build FAP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: flipperzero-lightmeter
        submodules: 'true'
        
    - name: Build
      uses: oleksiikutuzov/flipperzero-ufbt-action@v0.3
      with:
        fap-dir: flipperzero-lightmeter
