name: "FAP: Build and lint"
on: [push, pull_request]
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: 'ufbt: Build'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with ufbt GB Cartridge
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app-gb-cartridge
        with:
          # Set to 'release' to build for latest published release version
          sdk-channel: release
          app-dir: ./flipper_companion_apps/applications/external/malveke_gb_cartridge/
      - name: Build with ufbt GB Link Camera
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app-link-camera
        with:
          # Set to 'release' to build for latest published release version
          sdk-channel: release
          app-dir: ./flipper_companion_apps/applications/external/malveke_gb_link_camera/
      - name: Build with ufbt GB Live Camera
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app-live-camera
        with:
          # Set to 'release' to build for latest published release version
          sdk-channel: release
          app-dir: ./flipper_companion_apps/applications/external/malveke_gb_live_camera/
      - name: Build with ufbt GBA Cartridge
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app-gba-cartridge
        with:
          # Set to 'release' to build for latest published release version
          sdk-channel: release
          app-dir: ./flipper_companion_apps/applications/external/malveke_gba_cartridge/
      - name: Upload app artifacts GB Cartridge
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app-gb-cartridge.outputs.suffix }}
          path: ${{ steps.build-app-gb-cartridge.outputs.fap-artifacts }}
      - name: Upload app artifacts GB Link Camera
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app-link-camera.outputs.suffix }}
          path: ${{ steps.build-app-link-camera.outputs.fap-artifacts }}
      - name: Upload app artifacts GB Live Camera
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app-live-camera.outputs.suffix }}
          path: ${{ steps.build-app-live-camera.outputs.fap-artifacts }}
      - name: Upload app artifacts GBA Cartridge
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app-gba-cartridge.outputs.suffix }}
          path: ${{ steps.build-app-gba-cartridge.outputs.fap-artifacts }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.build-app-gb-cartridge.outputs.fap-artifacts }}
            ${{ steps.build-app-link-camera.outputs.fap-artifacts }}
            ${{ steps.build-app-live-camera.outputs.fap-artifacts }}
            ${{ steps.build-build-app-gba-cartridge.outputs.fap-artifacts }}