name: 'Generate documentation with Doxygen'

on:
  pull_request:
  push:
    branches:
      - dev
    tags:
      - '*'

env:
  TARGETS: f7 f18
  DEFAULT_TARGET: f7

jobs:
  doxygen:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Wipe workspace'
        run: find ./ -mount -maxdepth 1 -exec rm -rf {} \;

      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: 'Get commit details'
        id: names
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TYPE="pull"
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            TYPE="tag"
          else
            TYPE="other"
          fi
          python3 scripts/get_env.py "--event_file=${{ github.event_path }}" "--type=$TYPE"

      - name: 'Install requirements'
        run: |
          sudo apt install -y doxygen
          sudo python3 -m pip install sphinx sphinx_rtd_theme doxysphinx sphinx-multiversion myst-parser

      - name: 'Build the docs'
        run: |
          pushd flipperzero-documentation
          doxygen Doxyfile-awesome.cfg
          doxysphinx build doxygen/html sphinx_out/ Doxyfile-awesome.cfg
          popd
          sphinx-multiversion flipperzero-documentation flipperzero-documentation/sphinx_out/
          pushd flipperzero-documentation
          doxysphinx build doxygen/html sphinx_out/${BRANCH_NAME}/doxygen/html/ Doxyfile-awesome.cfg
          popd

      - name: 'Upload to Github Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flipperzero-documentation/sphinx_out/${{steps.names.outputs.branch_name}}/doxygen/html/
          publish_branch: docs
