name: Flipper Zero CI

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone ufbt
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/flipperdevices/flipperzero-ufbt.git ../ufbt
      - name: Ufbt Build App
        run: |
          ../ufbt/ufbt "fap_$(grep -o 'appid="[a-zA-Z0-9]\+"' application.fam | awk -F '"' '{print $2}')"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ../ufbt/.ufbt/build/**/*.fap
