name: Build

on:
  push:
    branches: [main]

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: "ufbt: Build for dev channel"

    strategy:
      matrix:
        include:
          - name: OFW dev
            sdk-channel: dev
          - name: Unleashed dev
            sdk-index-url: https://up.unleashedflip.com/directory.json
            sdk-channel: dev
          - name: Momentum dev
            sdk-index-url: https://up.momentum-fw.dev/firmware/directory.json
            sdk-channel: dev

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: FindMyFlipper

      - name: 'ufbt: Build for ${{ matrix.name }}'
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app
        with:
          # Set to 'release' to build for latest published release version
          sdk-channel: ${{ matrix.sdk-channel }}
          sdk-index-url: ${{ matrix.sdk-index-url }}
          app-dir: FindMyFlipper

      - name: Get commit message
        run: echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV
          
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
            draft: true
            name: ${{ env.COMMIT_MESSAGE }}
            token: ${{ secrets.GITHUB_TOKEN }}
            files: ${{ steps.build-app.outputs.fap-artifacts }}
            generate_release_notes: true
            
