name: "Release PR - Lint & Build Test"
on:
  pull_request:
    branches:
      - main
jobs:
  ufbt-test-build-action:
    runs-on: ubuntu-latest
    # The following builds must pass before release is accepted:
    strategy:
      matrix:
        include:
          - name: "dev"
            sdk-channel: dev

          - name: "rc"
            sdk-channel: rc

          - name: "release"
            sdk-channel: release

    name: "PR Build: ${{ matrix.name }}"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Flipper Zero ufbt action
      # https://github.com/flipperdevices/flipperzero-ufbt-action
      - name: "Build"
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          app-dir: ./fap
          sdk-channel: ${{ matrix.sdk-channel }}

      - name: "Lint"
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          app-dir: ./fap
          skip-setup: true
          task: lint

      - name: "Create FAP Download Pre Release (${{ matrix.name }})"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.name }}-${{ steps.build-app.outputs.suffix }}.zip
          path: ${{ steps.build-app.outputs.fap-artifacts }}
