name: 'unit_tests'

on:
  push:
    branches:
      - doom/2887_actions_units
    tags:
      - '*'
  pull_request:

env:
  TARGETS: f7
  DEFAULT_TARGET: f7

jobs:
  main:
    runs-on: [self-hosted, FlipperZeroTest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Compile unit tests firmware'
        continue-on-error: true
        run: |
          ./fbt FIRMWARE_APP_SET=unit_tests flash_usb FORCE=1

      - name: 'Copy unit tests to flipper'
        continue-on-error: true
        run: |
          sleep 30
          ./scripts/storage.py -p /dev/ttyACM0 send assets/unit_tests /ext/unit_tests

      - name: 'Run units and validate results'
        continue-on-error: true
        run: |
          cd /home/actions-runner/actions-runner/QA-flipper-units
          /home/actions-runner/.local/bin/poetry run python3 run_units.py /dev/ttyACM0
